### ISSUE TITLE
🐞 - [Ionic] content doesn't scroll to anchor with "smoothScroll" option enabled

### ISSUE THREAD

**Issue by Saqib92** [hakimio/ngx-ui-tour#104]
### Which ngx-ui-tour-* package is the source of the bug?

ionic

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ionic6-angular13-qofjib?file=src/app/app.component.ts

### Description

When using in ionic project it pushes the header upside and then user is not able to see header. its not scrolling back. 

Actual Header:

![Screenshot 2023-02-03 at 1 24 24 PM](https://user-images.githubusercontent.com/7135885/216549283-8613437c-3355-4cba-a970-5bee38e38820.png)

After Tour starts:
![Screenshot 2023-02-03 at 1 25 26 PM](https://user-images.githubusercontent.com/7135885/216549441-d6633de9-03b9-4564-96fb-92091d5444b9.png)

Will Create Stackblitz with this issue. 

## ALSO i have 2 steps on home page and 3rd and 4 step on about page is is not woking on multi page. 

throwing this error:

> Can't attach to unregistered anchor with id thirdStep

### Angular version

15

### Ngx UI Tour version

1.1.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by hakimio** [comment]
What tour configuration are you using? Did you disable page scrolling using UI tour? What styles are messing your header? Can you provide reproduction of the issue?

**Comment by Saqib92** [comment]
> Did you set `route` config on your `thirdStep` and did you import `TourAnchorIonPopoverDirective` in your "About" page module/component?

No i missed this step. Didn't find these in ionic section of documentations. Will try this. 

and will make stackblitz for header issue. Give me some time.

**Comment by hakimio** [comment]
`route` config is documented in [the API documentation section](https://hakimio.github.io/ngx-ui-tour/ion-popover/API#step-config) and your IDE should complain when you are using directive without importing it.

**Comment by hakimio** [comment]
I guess the issue is that the tour scrolls your container to reveal the anchor element, which results in some unexpected results for you. You can either disable scroll to anchor in the tour or fix your container CSS so that your header doesn't scroll up.

**Comment by Saqib92** [comment]
Stackblitz link added but its not working in stackblitz. 
But was working in my project. My Ionic header is added in stackblitz.

**Comment by hakimio** [comment]
So, can you reproduce it on StackBlitz or GitHub or not? Why is your header scrolling up in the first place - shouldn't it be fixed?

**Comment by hakimio** [comment]
That's what happens when I try to `scrollIntoView()` your `ion-title` on StackBlitz:
![image](https://user-images.githubusercontent.com/768105/216629573-0aee8ab2-73d4-4749-8646-a8c8c682d4b7.png)

Maybe you should try to attach `tourAnchor` to a different element or see why it scrolls funny on your app?

**Comment by Saqib92** [comment]
> So, can you reproduce it on StackBlitz or GitHub or not? Why is your header scrolling up in the first place - shouldn't it be fixed?

No, because i an using condensed header:
https://ionicframework.com/docs/api/header#condensed-header

in this when user scrolls header goes upside. 

I will share Github soon. i wan unable to use library on stackblitz.

**Comment by hakimio** [comment]
I have released `v10.2.0` of the library. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v10.2.0) to see if it fixes any issues relevant to you.

**Comment by Saqib92** [comment]
Here is my GitHub Repo:
https://github.com/Saqib92/ngx-ui-tour-ionic-icssue

After updating to latest version it is working better but still facing some issues with some options like:

```
enableBackdrop: true,
smoothScroll: true
```

You can test with all different options as well. 
If i only enable backdrop the popover is not visible. 
if i use backdrop with smooth scroll it not working. etc.

**Comment by hakimio** [comment]
This seems to be Ionic shadow DOM related issue. Scroll events are not emitted when listening to them on `window` level (`window.addEventListener('scroll', () => console.log('scroll!'))`). A new setting is needed to specify the scrollable container element in this case.
Anyway, were your other issues fixed in `v1.2.0`?

**Comment by hakimio** [comment]
Also, the issue with popover hidden behind backdrop was fixed in `v1.2.0`. Might have to delete your Angular `.cache` folder if it still appears hidden after upgrade.
I could not reproduce this issue in your demo project. The only issue I could see was with `smoothScroll`.

**Comment by Saqib92** [comment]
> This seems to be Ionic shadow DOM related issue. Scroll events are not emitted when listening to them on `window` level (`window.addEventListener('scroll', () => console.log('scroll!'))`). A new setting is needed to specify the scrollable container element in this case. Anyway, were your other issues fixed in `v1.2.0`?

Yes. other issues are fixed, and it is now working. Thank you for support. I am keeping this issue open for `smoothScroll` option. 
Thanks again.

**Comment by hakimio** [comment]
Released a fix for `smoothScroll` issue in `v1.3.0`. Let me know if it works for you.

**Comment by hakimio** [comment]
Might have closed a bit too fast. Most likely there are still issues with `smoothScroll` on multi-route tours.

**Comment by hakimio** [comment]
Published `v1.3.1` which should properly fix the issue.

**Comment by Saqib92** [comment]
Again facing Header Issue after Upgrading to `v1.3.1`. when it scrolls down to page my header messed up.

**Comment by hakimio** [comment]
You can use [the default tour options](https://hakimio.github.io/ngx-ui-tour/ion-popover/Misc#defauls), you don't have to repeat the same config in all steps.
Anyway, do you get the same behavior when you just manually call one of the following:
```
myAnchorEl.scrollIntoView({block: "start", inline: "nearest"});
myAnchorEl.scrollIntoView({block: "end", inline: "nearest"});
```
Also, you can try `centerAnchorOnScroll` option to see if it works better for you.

**Comment by Saqib92** [comment]
Issue solved by removing: `[fullscreen]="true"` from `ion-content`. now header behaves correctly.
